# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 488011229e134513d0f6516efd5a2ff338269dd9e1cc2ba6493c74b64bd9b29fac638601e39f8da1b260475724c0ee754456464b2f82a57f849e0e5a5d43294c

test:
  secret_key_base: e716f2dbc454a9b89c9981b4da5f73d1e9fe017f442ced8125db52ca7459043cb89282d1196c06de616a7cb4070045b58b81e93cc61f510fc13d9f8a78d1c120

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
